AWSTemplateFormatVersion: "2010-09-09"

Resources:
  TrainingSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: training-content-topic
      DisplayName: TrainingContent-Topic

  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: "admin@training.com"
      Protocol: email
      TopicArn: !Ref TrainingSNSTopic

Outputs:
  TopicARN:
    Description: ARN of the newly created SNS Topic
    Value: !Ref TrainingSNSTopic

  QueueName:
    Description: Name of the newly created SNS Topic
    Value: !GetAtt TrainingSNSTopic.TopicName