server:
  port:
    8082
spring:
  application:
    name: printer_service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    url: jdbc:mysql://localhost:3306/printer_db
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update